const CLIENT_ID = "efd6708d9ea94c96b31dc5657ce36c60"
const SECRET = "3swK4rafbjlqdUXfAkp6wbO4KTXi8yFi"
const tokenUrl = "https://oauth.battle.net/token";
const baseUrl = "https://us.api.blizzard.com"

// Constantes pour les races
const HUMAIN = "Humain";
const NAIN = "Nain";
const ELFE_DE_LA_NUIT = "Elfe de la nuit";
const GNOME = "Gnome";
const DRAENEI = "Draeneï";
const WORGEN = "Worgen";
const PANDAREN = "Pandaren";
const DRACTHYR = "Dracthyr";
const ORC = "Orc";
const REPROUVE = "Réprouvé";
const TAUREN = "Tauren";
const TROLL = "Troll";
const ELFE_DE_SANG = "Elfe de sang";
const GOBELIN = "Gobelin";
const ELFE_DU_VIDE = "Elfe du Vide";
const DRAENEI_SANCTEFORGE = "Draeneï sancteforge";
const NAIN_SOMBREFER = "Nain Sombrefer";
const KUL_TIRAN = "Kul Tiran";
const MECAGNOME = "Mécagnome";
const SACRENUIT = "Sacrenuit";
const TAUREN_DE_HAUT_ROC = "Tauren de Haut-Roc";
const ORC_MAGHAR = "Orc Mag'har";
const TROLL_ZANDALARI = "Troll Zandalari";
const VULPERIN = "Vulpérin";
const TELLURIEN = "Tellurien";

// Constantes pour les classes
const GUERRIER = "Guerrier";
const PALADIN = "Paladin";
const CHASSEUR = "Chasseur";
const VOLEUR = "Voleur";
const PRETRE = "Prêtre";
const DEMONISTE = "Démoniste";
const CHAMAN = "Chaman";
const DRUIDE = "Druide";
const CHEVALIER_DE_LA_MORT = "Chevalier de la mort";
const MOINE = "Moine";
const CHASSEUR_DE_DEMONS = "Chasseur de démons";
const EVOCATEUR = "Évocateur";

// Constantes pour les spécialisations
const ARMES = "Armes";
const FUREUR = "Fureur";
const PROTECTION = "Protection";
const SACRE = "Sacré";
const VINDICTE = "Vindicte";
const MAITRISE_DES_BETES = "Maîtrise des bêtes";
const PRECISION = "Précision";
const SURVIE = "Survie";
const ASSASSINAT = "Assassinat";
const HORS_LA_LOI = "Hors-la-loi";
const FINESSE = "Finesse";
const DISCIPLINE = "Discipline";
const OMBRE = "Ombre";
const AFFLICTION = "Affliction";
const DEMONOLOGIE = "Démonologie";
const DESTRUCTION = "Destruction";
const ELEMENTAIRE = "Élémentaire";
const AMELIORATION = "Amélioration";
const RESTAURATION = "Restauration";
const EQUILIBRE = "Équilibre";
const FAROUCHE = "Farouche";
const GARDIEN = "Gardien";
const SANG = "Sang";
const GIVRE = "Givre";
const IMPIE = "Impie";
const MAITRE_BRASSEUR = "Maître brasseur";
const TISSE_BRUME = "Tisse-brume";
const MARCHE_VENT = "Marche-vent";
const DEVASTATION = "Dévastation";
const VENGEANCE = "Vengeance";
const AUGMENTATION = "Augmentation";
const PRESERVATION = "Préservation";

// Mise à jour des objets
const classRaceMap = {
    [HUMAIN]: [GUERRIER, PALADIN, CHASSEUR, VOLEUR, PRETRE, DEMONISTE, CHEVALIER_DE_LA_MORT, MOINE],
    [NAIN]: [GUERRIER, PALADIN, CHASSEUR, VOLEUR, PRETRE, DEMONISTE, CHAMAN, CHEVALIER_DE_LA_MORT, MOINE],
    [ELFE_DE_LA_NUIT]: [GUERRIER, CHASSEUR, VOLEUR, PRETRE, DEMONISTE, DRUIDE, CHASSEUR_DE_DEMONS, CHEVALIER_DE_LA_MORT, MOINE],
    [GNOME]: [GUERRIER, CHASSEUR, VOLEUR, PRETRE, DEMONISTE, CHEVALIER_DE_LA_MORT, MOINE],
    [DRAENEI]: [GUERRIER, PALADIN, CHASSEUR, VOLEUR, PRETRE, DEMONISTE, CHAMAN, CHEVALIER_DE_LA_MORT, MOINE],
    [WORGEN]: [GUERRIER, CHASSEUR, VOLEUR, PRETRE, DEMONISTE, DRUIDE, CHEVALIER_DE_LA_MORT, MOINE],
    [PANDAREN]: [GUERRIER, CHASSEUR, VOLEUR, PRETRE, DEMONISTE, CHAMAN, CHEVALIER_DE_LA_MORT, MOINE],
    [DRACTHYR]: [EVOCATEUR],
    [ORC]: [GUERRIER, CHASSEUR, VOLEUR, PRETRE, DEMONISTE, CHAMAN, CHEVALIER_DE_LA_MORT, MOINE],
    [REPROUVE]: [GUERRIER, CHASSEUR, VOLEUR, PRETRE, DEMONISTE, CHEVALIER_DE_LA_MORT, MOINE],
    [TAUREN]: [GUERRIER, PALADIN, CHASSEUR, VOLEUR, PRETRE, DEMONISTE, CHAMAN, DRUIDE, CHEVALIER_DE_LA_MORT, MOINE],
    [TROLL]: [GUERRIER, CHASSEUR, VOLEUR, PRETRE, DEMONISTE, CHAMAN, DRUIDE, CHEVALIER_DE_LA_MORT, MOINE],
    [ELFE_DE_SANG]: [GUERRIER, PALADIN, CHASSEUR, VOLEUR, PRETRE, DEMONISTE, CHEVALIER_DE_LA_MORT, MOINE, CHASSEUR_DE_DEMONS],
    [GOBELIN]: [GUERRIER, CHASSEUR, VOLEUR, PRETRE, DEMONISTE, CHAMAN, CHEVALIER_DE_LA_MORT, MOINE],
    [ELFE_DU_VIDE]: [GUERRIER, CHASSEUR, VOLEUR, PRETRE, DEMONISTE, CHEVALIER_DE_LA_MORT, MOINE],
    [DRAENEI_SANCTEFORGE]: [GUERRIER, PALADIN, CHASSEUR, VOLEUR, PRETRE, DEMONISTE, CHEVALIER_DE_LA_MORT, MOINE],
    [NAIN_SOMBREFER]: [GUERRIER, PALADIN, CHASSEUR, VOLEUR, PRETRE, DEMONISTE, CHAMAN, CHEVALIER_DE_LA_MORT, MOINE],
    [KUL_TIRAN]: [GUERRIER, CHASSEUR, VOLEUR, PRETRE, DEMONISTE, CHAMAN, DRUIDE, CHEVALIER_DE_LA_MORT, MOINE],
    [MECAGNOME]: [GUERRIER, CHASSEUR, VOLEUR, PRETRE, DEMONISTE, CHEVALIER_DE_LA_MORT, MOINE],
    [SACRENUIT]: [GUERRIER, CHASSEUR, VOLEUR, PRETRE, DEMONISTE, CHEVALIER_DE_LA_MORT, MOINE],
    [TAUREN_DE_HAUT_ROC]: [GUERRIER, CHASSEUR, VOLEUR, PRETRE, DEMONISTE, CHAMAN, DRUIDE, CHEVALIER_DE_LA_MORT, MOINE],
    [ORC_MAGHAR]: [GUERRIER, CHASSEUR, VOLEUR, PRETRE, DEMONISTE, CHAMAN, CHEVALIER_DE_LA_MORT, MOINE],
    [TROLL_ZANDALARI]: [GUERRIER, PALADIN, CHASSEUR, VOLEUR, PRETRE, DEMONISTE, CHAMAN, DRUIDE, CHEVALIER_DE_LA_MORT, MOINE],
    [VULPERIN]: [GUERRIER, CHASSEUR, VOLEUR, PRETRE, DEMONISTE, CHAMAN, CHEVALIER_DE_LA_MORT, MOINE],
    [TELLURIEN]: [GUERRIER, PALADIN, CHASSEUR, VOLEUR, PRETRE, DEMONISTE, CHAMAN, MOINE]
};

const specsByClass = {
    [GUERRIER]: [ARMES, FUREUR, PROTECTION],
    [PALADIN]: [SACRE, PROTECTION, VINDICTE],
    [CHASSEUR]: [MAITRISE_DES_BETES, PRECISION, SURVIE],
    [VOLEUR]: [ASSASSINAT, HORS_LA_LOI, FINESSE],
    [PRETRE]: [DISCIPLINE, SACRE, OMBRE],
    [DEMONISTE]: [AFFLICTION, DEMONOLOGIE, DESTRUCTION],
    [CHAMAN]: [ELEMENTAIRE, AMELIORATION, RESTAURATION],
    [DRUIDE]: [EQUILIBRE, FAROUCHE, GARDIEN, RESTAURATION],
    [CHEVALIER_DE_LA_MORT]: [SANG, GIVRE, IMPIE],
    [MOINE]: [MAITRE_BRASSEUR, TISSE_BRUME, MARCHE_VENT],
    [CHASSEUR_DE_DEMONS]: [DEVASTATION, VENGEANCE],
    [EVOCATEUR]: [PRESERVATION, DEVASTATION, AUGMENTATION]
};

export {
    classRaceMap,
    specsByClass,
    CLIENT_ID,
    SECRET,
    tokenUrl,
    baseUrl
};